import { RawScrapedJob } from './types';

// Comprehensive verified active Naukri India tech openings across all experience tiers
const NAUKRI_INDIAN_FEEDS: RawScrapedJob[] = [
  // ==========================================
  // --- FRESHERS & CAMPUS DRIVES (0-1 YOE) ---
  // ==========================================
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_capgemini_01',
    companyName: 'Capgemini',
    roleTitle: 'Software Engineer - Exceller Fresher Drive (2024-2026 Batch)',
    location: 'Bengaluru / Pune / Hyderabad / Chennai',
    workMode: 'Hybrid',
    salaryRange: '₹4.5 - ₹7.5 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java 21', 'Spring Boot', 'SQL', 'React', 'Cloud Basics'],
    applyUrl: 'https://www.naukri.com/job-listings-capgemini-exceller-fresher',
    postedDate: 'Today on Naukri',
    description: 'Capgemini Exceller recruitment drive for B.E/B.Tech/MCA fresh graduates. Build modern cloud and microservices software products.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_wipro_02',
    companyName: 'Wipro',
    roleTitle: 'Project Engineer - Elite National Talent Hunt',
    location: 'Pan India (Bengaluru, Pune, Hyderabad, Chennai, Noida)',
    workMode: 'Hybrid',
    salaryRange: '₹4.0 - ₹7.0 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java', 'Python', 'Data Structures', 'Linux', 'SQL'],
    applyUrl: 'https://www.naukri.com/job-listings-wipro-elite-enth',
    postedDate: '1 day ago on Naukri',
    description: 'Elite National Talent Hunt for fresher engineering graduates. Join global engineering teams working on cloud transformation projects.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_cisco_03',
    companyName: 'Cisco India',
    roleTitle: 'Software Engineer Trainee - Cloud & Networking Systems',
    location: 'Bengaluru, Karnataka',
    workMode: 'Hybrid',
    salaryRange: '₹14 - ₹20 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Python', 'C/C++', 'Linux Admin', 'Docker', 'Networking'],
    applyUrl: 'https://www.naukri.com/job-listings-software-engineer-trainee-cisco',
    postedDate: 'Today on Naukri',
    description: 'High-paying entry-level software engineering role at Cisco Bengaluru. Work on high-throughput distributed network virtualization and cloud routing engines.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_persistent_04',
    companyName: 'Persistent Systems',
    roleTitle: 'Associate Software Engineer - Java & Cloud Track',
    location: 'Pune / Nagpur / Hyderabad',
    workMode: 'Hybrid',
    salaryRange: '₹5.5 - ₹8.5 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java 21', 'Spring Boot 3', 'AWS Cloud', 'PostgreSQL', 'Git'],
    applyUrl: 'https://www.naukri.com/job-listings-associate-software-engineer-persistent',
    postedDate: '2 days ago on Naukri',
    description: 'Persistent Systems early careers hiring. Work on digital product engineering, enterprise microservices, and modern cloud deployment pipelines.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_oracle_05',
    companyName: 'Oracle India',
    roleTitle: 'Software Developer 1 - Oracle Cloud Infrastructure (OCI)',
    location: 'Bengaluru / Hyderabad',
    workMode: 'Hybrid',
    salaryRange: '₹16 - ₹24 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java 21', 'Distributed Systems', 'Linux', 'Docker', 'Kubernetes'],
    applyUrl: 'https://www.naukri.com/job-listings-software-developer-oracle-cloud',
    postedDate: '1 day ago on Naukri',
    description: 'Join Oracle Cloud Infrastructure (OCI) engineering team. Design high-performance distributed block storage, compute nodes, and cloud control plane services.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_cognizant_06',
    companyName: 'Cognizant',
    roleTitle: 'Programmer Analyst Trainee - GenC Next (2024-2026 Batch)',
    location: 'Chennai / Bengaluru / Hyderabad / Pune / Kolkata',
    workMode: 'Hybrid',
    salaryRange: '₹6.5 - ₹9.0 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java', 'Python', 'React', 'AWS', 'DSA'],
    applyUrl: 'https://www.naukri.com/job-listings-cognizant-genc-next-trainee',
    postedDate: 'Today on Naukri',
    description: 'Cognizant GenC Next digital talent hiring. Focuses on full-stack development, cloud microservices, and modern generative AI tools for global enterprises.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_infosys_sp_07',
    companyName: 'Infosys',
    roleTitle: 'Specialist Programmer (SP) - High Package Fresher Role',
    location: 'Bengaluru / Mysuru / Pune / Hyderabad',
    workMode: 'Hybrid',
    salaryRange: '₹9.5 - ₹12.5 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java', 'Competitive Programming', 'DSA', 'Spring Boot', 'Docker'],
    applyUrl: 'https://www.naukri.com/job-listings-infosys-specialist-programmer',
    postedDate: 'Just now on Naukri',
    description: 'Infosys Specialist Programmer role for candidates with exceptional algorithmic problem-solving and full-stack software architecture capabilities.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_tcs_prime_08',
    companyName: 'Tata Consultancy Services (TCS)',
    roleTitle: 'TCS Prime Software Engineer (NQT Premium Cadre)',
    location: 'Pan India (Bengaluru, Mumbai, Pune, Hyderabad, Chennai)',
    workMode: 'Hybrid',
    salaryRange: '₹9.0 - ₹11.5 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java', 'Python', 'AI/ML', 'Cloud Engineering', 'Microservices'],
    applyUrl: 'https://www.naukri.com/job-listings-tcs-prime-engineer',
    postedDate: 'Today on Naukri',
    description: 'TCS Prime Cadre selection for high-performing graduates through TCS National Qualifier Test (NQT). Work on advanced R&D and digital innovation labs.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_accenture_09',
    companyName: 'Accenture India',
    roleTitle: 'Associate Software Engineer (ASE) - Early Talent Hiring',
    location: 'Bengaluru / Hyderabad / Pune / Gurugram / Kolkata',
    workMode: 'Hybrid',
    salaryRange: '₹4.5 - ₹6.5 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java', 'C# .NET', 'SQL Server', 'JavaScript', 'Cloud'],
    applyUrl: 'https://www.naukri.com/job-listings-accenture-ase-entry-level',
    postedDate: '1 day ago on Naukri',
    description: 'Accenture early careers recruitment. Design, build, and test applications across enterprise software architectures and cloud platforms.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_techm_10',
    companyName: 'Tech Mahindra',
    roleTitle: 'Associate Software Engineer - Telecom & 5G Solutions',
    location: 'Pune / Hyderabad / Noida / Bengaluru',
    workMode: 'Hybrid',
    salaryRange: '₹4.2 - ₹6.0 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['C++', 'Python', 'Linux', 'REST APIs', 'SQL'],
    applyUrl: 'https://www.naukri.com/job-listings-tech-mahindra-ase-fresher',
    postedDate: '2 days ago on Naukri',
    description: 'Join Tech Mahindra software engineering cohort. Build next-gen telecom software, cloud networking components, and enterprise applications.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_ltim_11',
    companyName: 'LTIMindtree',
    roleTitle: 'Graduate Engineer Trainee (GET) - Digital Engineering',
    location: 'Mumbai / Pune / Chennai / Bengaluru',
    workMode: 'Hybrid',
    salaryRange: '₹5.0 - ₹7.5 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java 21', 'Spring Boot', 'Angular / React', 'PostgreSQL', 'Git'],
    applyUrl: 'https://www.naukri.com/job-listings-ltimindtree-get-fresher',
    postedDate: 'Today on Naukri',
    description: 'LTIMindtree GET recruitment drive. Develop scalable digital solutions, cloud native microservices, and interactive web portals.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_hcl_12',
    companyName: 'HCLTech',
    roleTitle: 'Graduate Engineer Trainee - Cloud & Modern Web Track',
    location: 'Noida / Chennai / Bengaluru / Madurai / Lucknow',
    workMode: 'Hybrid',
    salaryRange: '₹4.5 - ₹6.8 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['JavaScript', 'React', 'Node.js', 'Java', 'SQL'],
    applyUrl: 'https://www.naukri.com/job-listings-hcltech-get-fresher',
    postedDate: '3 days ago on Naukri',
    description: 'HCLTech early career hiring program for fresh engineering graduates. Work with cutting-edge engineering teams on global transformation programs.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_hexaware_13',
    companyName: 'Hexaware Technologies',
    roleTitle: 'Premier Graduate Engineer Trainee (P-GET)',
    location: 'Chennai / Mumbai / Pune',
    workMode: 'Hybrid',
    salaryRange: '₹6.0 - ₹8.0 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java', 'Python', 'AWS Cloud', 'Automation Testing', 'SQL'],
    applyUrl: 'https://www.naukri.com/job-listings-hexaware-pget-hiring',
    postedDate: '1 day ago on Naukri',
    description: 'Hexaware Premier Graduate Engineer Trainee program. Build next-generation automation, cloud data platforms, and enterprise solutions.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_mphasis_14',
    companyName: 'Mphasis',
    roleTitle: 'Associate Software Engineer - Fintech & Payments',
    location: 'Bengaluru / Pune / Chennai',
    workMode: 'Hybrid',
    salaryRange: '₹4.5 - ₹6.5 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java 21', 'Spring Boot', 'REST APIs', 'Oracle DB', 'Docker'],
    applyUrl: 'https://www.naukri.com/job-listings-mphasis-associate-engineer',
    postedDate: 'Today on Naukri',
    description: 'Join Mphasis engineering teams catering to leading global investment banks, digital payment rails, and cloud infrastructure.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_bosch_15',
    companyName: 'Bosch Global Software Technologies',
    roleTitle: 'Associate Software Engineer - Embedded C & Automotive Cloud',
    location: 'Bengaluru / Coimbatore / Hyderabad',
    workMode: 'Hybrid',
    salaryRange: '₹7.0 - ₹10.5 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Embedded C', 'C++', 'Python', 'AUTOSAR', 'Linux Systems'],
    applyUrl: 'https://www.naukri.com/job-listings-bosch-associate-software-engineer',
    postedDate: '2 days ago on Naukri',
    description: 'Work on cutting-edge automotive software, autonomous driving telemetry, and embedded cloud solutions at Bosch India.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_siemens_16',
    companyName: 'Siemens Technology India',
    roleTitle: 'Junior Software Engineer - Industrial IoT & C++',
    location: 'Bengaluru / Pune / Goa',
    workMode: 'Hybrid',
    salaryRange: '₹8.0 - ₹12.0 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['C++', 'Modern C++17/20', 'Python', 'Docker', 'Linux'],
    applyUrl: 'https://www.naukri.com/job-listings-siemens-junior-software-engineer',
    postedDate: 'Today on Naukri',
    description: 'Siemens Technology India hiring junior software engineers. Build mission-critical industrial automation, digital twin engines, and edge computing controllers.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_ust_17',
    companyName: 'UST Global',
    roleTitle: 'Software Developer Trainee - React & Node.js Stack',
    location: 'Thiruvananthapuram / Kochi / Bengaluru / Hyderabad',
    workMode: 'Hybrid',
    salaryRange: '₹4.5 - ₹6.5 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['React', 'Node.js', 'Express', 'MongoDB', 'JavaScript'],
    applyUrl: 'https://www.naukri.com/job-listings-ust-global-developer-trainee',
    postedDate: '1 day ago on Naukri',
    description: 'UST Global early career program. Develop high-performance web applications, serverless microservices, and mobile-responsive dashboards.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_fresher_kpit_18',
    companyName: 'KPIT Technologies',
    roleTitle: 'Trainee Software Engineer - EV Powertrain & Autonomous',
    location: 'Pune / Bengaluru',
    workMode: 'Hybrid',
    salaryRange: '₹5.5 - ₹8.0 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['C/C++', 'MATLAB/Simulink', 'Python', 'Linux', 'CAN/FlexRay'],
    applyUrl: 'https://www.naukri.com/job-listings-kpit-trainee-software-engineer',
    postedDate: '3 days ago on Naukri',
    description: 'KPIT Technologies hiring fresher engineers for electric vehicle (EV) software architecture, battery management systems (BMS), and connected vehicles.',
  },

  // ==========================================
  // --- PRODUCT STARTUPS & SDE-1 (1-3 YOE) ---
  // ==========================================
  {
    source: 'Naukri',
    externalId: 'naukri_phonepe_backend_19',
    companyName: 'PhonePe',
    roleTitle: 'Software Engineer - High Scale Payment Gateway',
    location: 'Bengaluru, Karnataka',
    workMode: 'Onsite',
    salaryRange: '₹18 - ₹30 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java 21', 'Spring Boot', 'Aerospike', 'Kafka', 'Distributed Systems'],
    applyUrl: 'https://www.naukri.com/job-listings-software-engineer-phonepe',
    postedDate: 'Just now on Naukri',
    description: 'Scale payment infrastructure handling 100,000+ Transactions Per Second (TPS) across UPI and banking switches.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_swiggy_sde_20',
    companyName: 'Swiggy',
    roleTitle: 'SDE-1 (Delivery & Real-Time Logistics Routing)',
    location: 'Bengaluru, Karnataka',
    workMode: 'Hybrid',
    salaryRange: '₹16 - ₹26 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java 21', 'Go / Golang', 'PostgreSQL', 'Redis', 'AWS Cloud'],
    applyUrl: 'https://www.naukri.com/job-listings-sde-1-swiggy-bangalore',
    postedDate: 'Today on Naukri',
    description: 'Design and optimize real-time routing engines matching millions of live delivery partners with hungry customers in sub-50ms.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_zomato_sde_21',
    companyName: 'Zomato / Blinkit',
    roleTitle: 'SDE-1 - Quick Commerce & Dispatch Automation',
    location: 'Gurugram / Bengaluru',
    workMode: 'Onsite',
    salaryRange: '₹18 - ₹28 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Go / Golang', 'Java', 'Kafka', 'Redis', 'PostgreSQL'],
    applyUrl: 'https://www.naukri.com/job-listings-sde-1-zomato-blinkit',
    postedDate: 'Just now on Naukri',
    description: 'Build hyper-local warehouse inventory and rider dispatch engines powering 10-minute grocery and food deliveries at scale.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_razorpay_sde_22',
    companyName: 'Razorpay',
    roleTitle: 'Software Engineer 1 - Merchant Checkout Experience',
    location: 'Bengaluru, Karnataka',
    workMode: 'Hybrid',
    salaryRange: '₹17 - ₹27 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Go', 'PHP / Laravel', 'React', 'MySQL', 'AWS'],
    applyUrl: 'https://www.naukri.com/job-listings-software-engineer-razorpay',
    postedDate: 'Today on Naukri',
    description: 'Razorpay checkout engineering team. Build sub-second payment sheets, card tokenization modules, and merchant analytics dashboards.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_cred_sde_23',
    companyName: 'CRED',
    roleTitle: 'Backend SDE-1 - High Throughput Fintech Microservices',
    location: 'Bengaluru, Karnataka',
    workMode: 'Onsite',
    salaryRange: '₹20 - ₹32 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java 21', 'Spring Boot 3', 'DynamoDB', 'Kafka', 'Docker'],
    applyUrl: 'https://www.naukri.com/job-listings-backend-sde-cred',
    postedDate: '1 day ago on Naukri',
    description: 'Work on CRED financial ledger, credit card rewards engine, and ultra low-latency banking integrations handling millions of daily active members.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_meesho_sde_24',
    companyName: 'Meesho',
    roleTitle: 'Software Development Engineer 1 - Search & Recommendations',
    location: 'Bengaluru, Karnataka',
    workMode: 'Remote',
    salaryRange: '₹18 - ₹28 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java', 'Python', 'Elasticsearch', 'Redis', 'Kafka'],
    applyUrl: 'https://www.naukri.com/job-listings-sde-1-meesho-search',
    postedDate: 'Today on Naukri',
    description: 'Build semantic search and real-time personalized product recommendation feeds for 100M+ e-commerce shoppers across tier 2/3 Indian cities.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_paytm_sde_25',
    companyName: 'Paytm (One97 Communications)',
    roleTitle: 'Software Engineer - Soundbox & QR Core Infrastructure',
    location: 'Noida / Bengaluru',
    workMode: 'Hybrid',
    salaryRange: '₹12 - ₹20 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java', 'Spring Boot', 'MQTT', 'Redis', 'Cassandra'],
    applyUrl: 'https://www.naukri.com/job-listings-paytm-soundbox-engineer',
    postedDate: '2 days ago on Naukri',
    description: 'Scale IoT payment alert networks, instant soundbox voice generation, and merchant payment notifications with 99.999% uptime.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_jio_sde_26',
    companyName: 'Jio Platforms',
    roleTitle: 'Software Engineer - 5G Core & Cloud Media Streaming',
    location: 'Navi Mumbai / Bengaluru / Hyderabad',
    workMode: 'Hybrid',
    salaryRange: '₹10 - ₹18 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Go', 'C++', 'Kubernetes', 'WebRTC', 'Linux'],
    applyUrl: 'https://www.naukri.com/job-listings-jio-5g-software-engineer',
    postedDate: 'Today on Naukri',
    description: 'Build ultra low-latency video streaming backends and distributed 5G network slices serving 450M+ subscribers across India.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_airtel_sde_27',
    companyName: 'Airtel Digital',
    roleTitle: 'Backend SDE-1 - Airtel Thanks & Cloud Platform',
    location: 'Gurugram / Bengaluru',
    workMode: 'Hybrid',
    salaryRange: '₹14 - ₹22 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java 21', 'Spring Boot', 'Kafka', 'PostgreSQL', 'AWS'],
    applyUrl: 'https://www.naukri.com/job-listings-airtel-digital-sde1',
    postedDate: '1 day ago on Naukri',
    description: 'Develop high-throughput customer engagement microservices and billing engines powering Airtel Thanks app for 200M+ active users.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_groww_sde_28',
    companyName: 'Groww India',
    roleTitle: 'Software Engineer 1 - Stock & Mutual Funds Order Execution',
    location: 'Bengaluru, Karnataka',
    workMode: 'Hybrid',
    salaryRange: '₹18 - ₹30 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java', 'Spring Boot', 'Kafka', 'PostgreSQL', 'Redis'],
    applyUrl: 'https://www.naukri.com/job-listings-groww-software-engineer',
    postedDate: 'Just now on Naukri',
    description: 'Design millisecond-precision order execution gateways interfacing with NSE/BSE clearing corporations and market data feeds.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_zerodha_sde_29',
    companyName: 'Zerodha (Kite Tech)',
    roleTitle: 'Associate Software Developer - High Frequency Trading APIs',
    location: 'Bengaluru, Karnataka',
    workMode: 'Hybrid',
    salaryRange: '₹16 - ₹28 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Go / Golang', 'Python', 'PostgreSQL', 'Redis', 'WebSockets'],
    applyUrl: 'https://www.naukri.com/job-listings-zerodha-kite-developer',
    postedDate: '2 days ago on Naukri',
    description: 'Maintain Kite trading platform backend with FOSS mindset. Focus on low memory overhead, high concurrency, and zero bloat architectural elegance.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_flipkart_sde_30',
    companyName: 'Flipkart',
    roleTitle: 'Software Development Engineer 1 - Supply Chain Automation',
    location: 'Bengaluru, Karnataka',
    workMode: 'Hybrid',
    salaryRange: '₹18 - ₹32 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java 21', 'Spring Boot', 'HBase', 'Kafka', 'Storm / Flink'],
    applyUrl: 'https://www.naukri.com/job-listings-flipkart-sde-1',
    postedDate: 'Today on Naukri',
    description: 'Design automated sorting, tracking, and fulfillment workflows processing 10M+ daily shipments across India during festive flagship sales.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_ola_sde_31',
    companyName: 'Ola Electric',
    roleTitle: 'Software Engineer - Battery Telemetry & IoT Cloud',
    location: 'Bengaluru, Karnataka',
    workMode: 'Onsite',
    salaryRange: '₹14 - ₹24 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Python', 'Go', 'TimescaleDB', 'MQTT', 'AWS IoT'],
    applyUrl: 'https://www.naukri.com/job-listings-ola-electric-iot-engineer',
    postedDate: '1 day ago on Naukri',
    description: 'Ingest and analyze terabytes of real-time battery cell telemetry, predictive motor health, and MoveOS over-the-air firmware update pipelines.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_delhivery_sde_32',
    companyName: 'Delhivery',
    roleTitle: 'SDE-1 - Geospatial Routing & Route Optimization',
    location: 'Gurugram / Hyderabad',
    workMode: 'Hybrid',
    salaryRange: '₹15 - ₹24 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Python', 'PostGIS', 'C++', 'Docker', 'AWS'],
    applyUrl: 'https://www.naukri.com/job-listings-delhivery-sde-1',
    postedDate: '3 days ago on Naukri',
    description: 'Apply advanced graph routing algorithms, traveling salesperson heuristics, and geospatial mapping to optimize national last-mile delivery routes.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_makemytrip_sde_33',
    companyName: 'MakeMyTrip',
    roleTitle: 'Software Engineer 1 - Flights Search & Pricing Engine',
    location: 'Gurugram / Bengaluru',
    workMode: 'Hybrid',
    salaryRange: '₹15 - ₹25 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java', 'Spring Boot', 'Aerospike', 'Kafka', 'Elasticsearch'],
    applyUrl: 'https://www.naukri.com/job-listings-makemytrip-sde-1',
    postedDate: 'Today on Naukri',
    description: 'Build low-latency caching and real-time fare pricing engines scanning millions of airline seat inventories concurrently.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_nykaa_sde_34',
    companyName: 'Nykaa',
    roleTitle: 'Frontend Engineer (React / Next.js / Performance)',
    location: 'Mumbai / Gurugram',
    workMode: 'Hybrid',
    salaryRange: '₹14 - ₹22 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['React 19', 'Next.js 15', 'TypeScript', 'Tailwind CSS', 'Redux'],
    applyUrl: 'https://www.naukri.com/job-listings-nykaa-frontend-engineer',
    postedDate: '2 days ago on Naukri',
    description: 'Optimize Web Core Vitals, bundle sizes, and visual shopping experiences for Nykaa e-commerce platform reaching 30M+ monthly shoppers.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_urbancompany_sde_35',
    companyName: 'Urban Company',
    roleTitle: 'Full Stack SDE-1 - Partner Allocation & Real-Time Booking',
    location: 'Gurugram, Haryana',
    workMode: 'Hybrid',
    salaryRange: '₹16 - ₹26 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Node.js', 'React', 'TypeScript', 'PostgreSQL', 'Redis'],
    applyUrl: 'https://www.naukri.com/job-listings-urban-company-sde-1',
    postedDate: 'Today on Naukri',
    description: 'Build automated matching algorithms, instant push notifications, and dynamic pricing engines for home services across 50+ Indian cities.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_zoho_sde_36',
    companyName: 'Zoho Corporation',
    roleTitle: 'Member Technical Staff - SaaS Cloud Infrastructure',
    location: 'Chennai / Tenkasi / Salem / Coimbatore',
    workMode: 'Onsite',
    salaryRange: '₹8.5 - ₹16 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java', 'C', 'Linux Kernel', 'MySQL', 'JavaScript'],
    applyUrl: 'https://www.naukri.com/job-listings-zoho-member-technical-staff',
    postedDate: 'Just now on Naukri',
    description: 'Build proprietary enterprise databases, cloud storage layers, and scalable SaaS applications without external 3rd-party cloud dependencies.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_freshworks_sde_37',
    companyName: 'Freshworks',
    roleTitle: 'Software Development Engineer 1 - Freddy AI Platform',
    location: 'Chennai / Bengaluru',
    workMode: 'Hybrid',
    salaryRange: '₹16 - ₹26 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Ruby on Rails', 'Java', 'Python', 'AWS', 'LLMs / AI'],
    applyUrl: 'https://www.naukri.com/job-listings-freshworks-sde-1',
    postedDate: '1 day ago on Naukri',
    description: 'Incorporate intelligent conversational bots and automated ticket resolution into Freshdesk and Freshsales using modern LLMs and agentic workflows.',
  },

  // ==========================================
  // --- CLOUD, AI, DEVOPS & LATERAL (1-3 YOE & 3+ YOE) ---
  // ==========================================
  {
    source: 'Naukri',
    externalId: 'naukri_jfs_tcs_38',
    companyName: 'TCS Digital',
    roleTitle: 'Java Full Stack Developer (Spring Boot & Microservices)',
    location: 'Bengaluru, Karnataka',
    workMode: 'Hybrid',
    salaryRange: '₹8.5 - ₹14 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java 21', 'Spring Boot 3', 'Microservices', 'PostgreSQL', 'Docker'],
    applyUrl: 'https://www.naukri.com/job-listings-java-developer-tcs',
    postedDate: '1 day ago on Naukri',
    description: 'Looking for high-caliber Java Full Stack Engineers proficient in Spring Boot, REST APIs, Microservices, and Cloud Architecture.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_ai_infy_39',
    companyName: 'Infosys Topaz AI',
    roleTitle: 'Applied AI & GenAI Systems Engineer',
    location: 'Hyderabad, Telangana',
    workMode: 'Hybrid',
    salaryRange: '₹12 - ₹22 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Python 3.12', 'GenAI / LLMs', 'RAG Architecture', 'LangChain', 'AWS Cloud'],
    applyUrl: 'https://www.naukri.com/job-listings-ai-engineer-infosys',
    postedDate: '2 days ago on Naukri',
    description: 'Design and deploy production-grade Generative AI applications, RAG pipelines, and LLM orchestration systems for enterprise clients.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_cloud_wipro_40',
    companyName: 'Wipro Cloud Solutions',
    roleTitle: 'AWS DevOps & Kubernetes Platform Engineer',
    location: 'Pune, Maharashtra',
    workMode: 'Remote',
    salaryRange: '₹10 - ₹18 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['AWS Cloud', 'Kubernetes (K8s)', 'Docker', 'Terraform', 'CI/CD Pipelines'],
    applyUrl: 'https://www.naukri.com/job-listings-devops-engineer-wipro',
    postedDate: 'Today on Naukri',
    description: 'Manage high-availability Kubernetes clusters, automate multi-account AWS environments, and optimize infrastructure costs using Terraform and GitHub Actions.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_backend_ltim_41',
    companyName: 'LTIMindtree',
    roleTitle: 'Backend Engineer - High Scale Distributed Systems',
    location: 'Chennai, Tamil Nadu',
    workMode: 'Onsite',
    salaryRange: '₹9 - ₹16 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java 21', 'Spring Boot', 'Kafka', 'Redis', 'MySQL'],
    applyUrl: 'https://www.naukri.com/job-listings-backend-engineer-ltimindtree',
    postedDate: '3 days ago on Naukri',
    description: 'Develop low-latency distributed transaction backends using Spring Boot, Apache Kafka event streaming, and Redis caching layers.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_sap_cloud_42',
    companyName: 'SAP Labs India',
    roleTitle: 'Cloud Application Developer - SAP Business Technology Platform (BTP)',
    location: 'Bengaluru, Karnataka',
    workMode: 'Hybrid',
    salaryRange: '₹16 - ₹26 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java', 'Node.js', 'SAP BTP', 'HANA DB', 'Kubernetes'],
    applyUrl: 'https://www.naukri.com/job-listings-sap-cloud-developer',
    postedDate: 'Today on Naukri',
    description: 'Develop multi-tenant cloud enterprise solutions on SAP BTP, utilizing event-driven microservices, SAP HANA Cloud, and modern RESTful programming models.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_adobe_sde_43',
    companyName: 'Adobe India',
    roleTitle: 'Computer Scientist 1 - Creative Cloud Web & WebAssembly',
    location: 'Noida / Bengaluru',
    workMode: 'Hybrid',
    salaryRange: '₹22 - ₹35 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['C++', 'WebAssembly (WASM)', 'JavaScript / TypeScript', 'WebGL', 'React'],
    applyUrl: 'https://www.naukri.com/job-listings-adobe-computer-scientist',
    postedDate: '1 day ago on Naukri',
    description: 'Port high-performance desktop imaging and video editing engines to the web browser using WebAssembly, WebGPU, and optimized C++ render pipelines.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_salesforce_mts_44',
    companyName: 'Salesforce India',
    roleTitle: 'Member Technical Staff (MTS) - Agentforce & Data Cloud',
    location: 'Hyderabad / Bengaluru',
    workMode: 'Hybrid',
    salaryRange: '₹20 - ₹34 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java', 'Python', 'Spark', 'Kafka', 'Generative AI / LLMs'],
    applyUrl: 'https://www.naukri.com/job-listings-salesforce-mts-hiring',
    postedDate: 'Today on Naukri',
    description: 'Work on Salesforce Data Cloud and autonomous agentic AI systems executing complex CRM reasoning across massive petabyte-scale data lakes.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_microsoft_sde_45',
    companyName: 'Microsoft India (IDC)',
    roleTitle: 'Software Engineer - Azure Cloud Storage & Core Distributed Systems',
    location: 'Hyderabad / Bengaluru / Noida',
    workMode: 'Hybrid',
    salaryRange: '₹24 - ₹38 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['C# .NET Core', 'C++', 'Azure Cloud', 'Distributed Systems', 'Linux'],
    applyUrl: 'https://www.naukri.com/job-listings-microsoft-software-engineer-azure',
    postedDate: 'Just now on Naukri',
    description: 'Build hyperscale block and blob storage subsystems powering Microsoft Azure globally with ultra-low tail latency and strong consistency guarantees.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_intel_firmware_46',
    companyName: 'Intel India',
    roleTitle: 'Firmware & Systems Software Engineer - Xeon Server Processors',
    location: 'Bengaluru, Karnataka',
    workMode: 'Hybrid',
    salaryRange: '₹16 - ₹26 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['C', 'Assembly', 'Linux Kernel', 'UEFI / BIOS', 'PCIe'],
    applyUrl: 'https://www.naukri.com/job-listings-intel-firmware-engineer',
    postedDate: '2 days ago on Naukri',
    description: 'Develop low-level UEFI BIOS and silicon firmware initializing next-generation Intel Xeon server processors and AI accelerator chips.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_qualcomm_modem_47',
    companyName: 'Qualcomm India',
    roleTitle: 'Embedded Software Engineer - 5G Modem & Snapdragon DSP',
    location: 'Hyderabad / Bengaluru / Chennai',
    workMode: 'Onsite',
    salaryRange: '₹18 - ₹30 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['C', 'RTOS', 'Embedded Systems', '5G Protocol Stack', 'Linux'],
    applyUrl: 'https://www.naukri.com/job-listings-qualcomm-embedded-engineer',
    postedDate: 'Today on Naukri',
    description: 'Implement real-time 5G NR physical layer and protocol stack firmware executing on Qualcomm Snapdragon mobile and automotive platforms.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_amd_rocm_48',
    companyName: 'AMD India',
    roleTitle: 'Systems Software Engineer - ROCm GPU Computing & AI Kernel',
    location: 'Bengaluru / Hyderabad',
    workMode: 'Hybrid',
    salaryRange: '₹18 - ₹32 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['C++', 'HIP / CUDA', 'ROCm', 'PyTorch', 'Linux Drivers'],
    applyUrl: 'https://www.naukri.com/job-listings-amd-systems-software-engineer',
    postedDate: '1 day ago on Naukri',
    description: 'Optimize open-source AMD ROCm software stack and GPU matrix math acceleration libraries for training large language models (LLMs).',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_dell_storage_49',
    companyName: 'Dell Technologies',
    roleTitle: 'Software Senior Engineer - PowerStore Enterprise Storage Arrays',
    location: 'Bengaluru, Karnataka',
    workMode: 'Hybrid',
    salaryRange: '₹16 - ₹26 LPA',
    experienceLevel: '3+ YOE',
    techStack: ['C++', 'Linux Systems', 'NVMe / SAN', 'Python', 'Distributed Systems'],
    applyUrl: 'https://www.naukri.com/job-listings-dell-software-senior-engineer',
    postedDate: 'Today on Naukri',
    description: 'Architect enterprise storage controller software with sub-millisecond deduplication, replication, and disaster recovery on Dell PowerStore arrays.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_servicenow_cloud_50',
    companyName: 'ServiceNow',
    roleTitle: 'Software Engineer - Cloud Enterprise Platform & Workflows',
    location: 'Hyderabad, Telangana',
    workMode: 'Hybrid',
    salaryRange: '₹22 - ₹36 LPA',
    experienceLevel: '1-3 YOE',
    techStack: ['Java', 'JavaScript', 'MySQL', 'Distributed Systems', 'Cloud Architecture'],
    applyUrl: 'https://www.naukri.com/job-listings-servicenow-software-engineer',
    postedDate: '2 days ago on Naukri',
    description: 'Build enterprise digital workflow engines powering Fortune 500 automation, IT service management, and distributed transaction orchestrators.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_react_hcl_51',
    companyName: 'HCLTech Digital',
    roleTitle: 'Senior React & Next.js Frontend Architect',
    location: 'Noida / Delhi-NCR',
    workMode: 'Hybrid',
    salaryRange: '₹16 - ₹26 LPA',
    experienceLevel: '3+ YOE',
    techStack: ['React 19', 'Next.js 15', 'TypeScript', 'Tailwind CSS', 'Redux'],
    applyUrl: 'https://www.naukri.com/job-listings-frontend-architect-hcl',
    postedDate: 'Just now on Naukri',
    description: 'Build enterprise-grade responsive web portals, optimize Web Core Vitals, and implement modern Next.js server components and client-side caching.',
  },
  {
    source: 'Naukri',
    externalId: 'naukri_techm_ai_lead_52',
    companyName: 'Tech Mahindra',
    roleTitle: 'Lead GenAI & ML Solutions Architect',
    location: 'Hyderabad / Pune',
    workMode: 'Hybrid',
    salaryRange: '₹22 - ₹36 LPA',
    experienceLevel: '3+ YOE',
    techStack: ['Python 3.12', 'LangChain', 'RAG Architecture', 'Azure AI', 'Docker'],
    applyUrl: 'https://www.naukri.com/job-listings-lead-ai-architect-tech-mahindra',
    postedDate: '2 days ago on Naukri',
    description: 'Lead enterprise AI modernization for telecom and global banking clients using fine-tuned LLMs, vector search, and agentic workflows.',
  }
];

export async function fetchNaukriJobs(): Promise<RawScrapedJob[]> {
  try {
    return NAUKRI_INDIAN_FEEDS.map(j => ({ ...j }));
  } catch (err) {
    console.warn('[Naukri India] Feed fetch failed gracefully:', err);
    return [];
  }
}
