import { RawScrapedJob } from './types';

// Unstop, Cuvette & Top Indian Campus & Off-Campus Hiring Drives
const UNSTOP_INDIAN_FEEDS: RawScrapedJob[] = [
  {
    source: 'Unstop',
    externalId: 'unstop_tcs_nqt_01',
    companyName: 'TCS (Tata Consultancy Services)',
    roleTitle: 'Graduate Trainee / Ninja & Digital SDE (2024, 2025 & 2026 Batch)',
    location: 'Pan India (Bengaluru, Pune, Hyderabad, Chennai, Kolkata)',
    workMode: 'Hybrid',
    salaryRange: '₹4.0 - ₹9.0 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java 21', 'Python 3.12', 'SQL', 'Data Structures & Algorithms', 'Cloud Basics'],
    applyUrl: 'https://unstop.com/competitions/tcs-national-qualifier-test-nqt-tata-consultancy-services',
    postedDate: 'Live Drive on Unstop',
    description: 'National Qualifier Test (NQT) for engineering graduates. Direct recruitment into TCS Ninja and TCS Digital high-scale product engineering business units. 2024, 2025 & 2026 Batch Eligible.',
  },
  {
    source: 'Unstop',
    externalId: 'unstop_infosys_genc_02',
    companyName: 'Infosys',
    roleTitle: 'Systems Engineer & Specialist Programmer (SP / DSE)',
    location: 'Bengaluru / Hyderabad / Mysuru',
    workMode: 'Hybrid',
    salaryRange: '₹6.5 - ₹11.5 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java 21', 'Spring Boot', 'Python', 'Algorithms', 'Microservices'],
    applyUrl: 'https://unstop.com/jobs/specialist-programmer-infosys-limited',
    postedDate: 'Active Campus Drive',
    description: 'Off-campus recruitment for Specialist Programmer (SP) and Digital Specialist Engineer (DSE) roles. Build enterprise cloud platforms and automation backends.',
  },
  {
    source: 'Unstop',
    externalId: 'unstop_cognizant_elevate_03',
    companyName: 'Cognizant',
    roleTitle: 'GenC Elevate & Next Full Stack Engineer (Fresher)',
    location: 'Chennai / Coimbatore / Pune / Hyderabad',
    workMode: 'Hybrid',
    salaryRange: '₹5.5 - ₹8.5 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java 21', 'React 19', 'Spring Boot 3', 'MySQL', 'Docker'],
    applyUrl: 'https://unstop.com/jobs/genc-elevate-full-stack-cognizant',
    postedDate: '1 day ago on Unstop',
    description: 'Cognizant GenC Elevate hiring drive. Work with modern enterprise stacks, cloud migrations, and full-stack software development.',
  },
  {
    source: 'Unstop',
    externalId: 'unstop_accenture_ase_04',
    companyName: 'Accenture',
    roleTitle: 'Associate Software Engineer (ASE) & Advanced ASE',
    location: 'Bengaluru / Pune / Gurugram / Hyderabad',
    workMode: 'Hybrid',
    salaryRange: '₹5.0 - ₹9.5 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java 21', 'Cloud AWS', 'Python', 'DevOps', 'SQL'],
    applyUrl: 'https://unstop.com/jobs/associate-software-engineer-accenture-india',
    postedDate: '2 days ago on Unstop',
    description: 'Accenture Innovation Centers hiring drive for entry-level developers. Hands-on training provided in cloud-native platforms, AI pipelines, and modern DevOps.',
  },
  {
    source: 'Unstop',
    externalId: 'unstop_amazon_intern_05',
    companyName: 'Amazon India',
    roleTitle: 'Software Development Engineer (SDE) Intern - 2026 Batch',
    location: 'Bengaluru / Hyderabad',
    workMode: 'Hybrid',
    salaryRange: '₹80,000 / mo + Benefits',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java 21', 'Data Structures & Algorithms', 'System Design', 'AWS Cloud'],
    applyUrl: 'https://unstop.com/internships/software-development-engineer-intern-amazon-india',
    postedDate: 'Today on Unstop',
    description: '6-Month paid SDE Internship with PPO conversion opportunity. Work directly with Amazon core retail, Prime, and AWS infrastructure teams.',
  },
  {
    source: 'Unstop',
    externalId: 'unstop_msft_intern_06',
    companyName: 'Microsoft IDC',
    roleTitle: 'Software Engineering Trainee - Cloud & AI Systems',
    location: 'Hyderabad, Telangana',
    workMode: 'Hybrid',
    salaryRange: '₹75,000 / mo',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['C# / Java', 'Azure Cloud', 'Python 3.12', 'GenAI / LLMs'],
    applyUrl: 'https://unstop.com/internships/software-engineer-trainee-microsoft-india',
    postedDate: '1 day ago on Unstop',
    description: 'Work alongside world-class engineers at Microsoft India Development Center (IDC) developing Copilot, Azure Infrastructure, and enterprise developer tooling.',
  },
  {
    source: 'Unstop',
    externalId: 'unstop_flipkart_fresher_07',
    companyName: 'Flipkart',
    roleTitle: 'Associate Software Engineer (Campus Fresher SDE-1)',
    location: 'Bengaluru, Karnataka',
    workMode: 'Onsite',
    salaryRange: '₹14 - ₹20 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java 21', 'Spring Boot 3', 'MySQL', 'Kafka', 'Docker'],
    applyUrl: 'https://unstop.com/jobs/associate-software-engineer-flipkart-india',
    postedDate: '2 days ago on Unstop',
    description: 'High-growth entry-level software engineering role for recent graduates and final year students. Build high-scale e-commerce checkout and catalogue engines.',
  },
  {
    source: 'Unstop',
    externalId: 'unstop_zoho_fresher_08',
    companyName: 'Zoho',
    roleTitle: 'Full Stack Web Developer - Fresher / Early Career',
    location: 'Chennai / Tenkasi / Coimbatore',
    workMode: 'Onsite',
    salaryRange: '₹6.5 - ₹10 LPA',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['Java 21', 'JavaScript', 'PostgreSQL', 'HTML5/CSS3', 'REST APIs'],
    applyUrl: 'https://unstop.com/jobs/full-stack-developer-zoho-corp',
    postedDate: '3 days ago on Unstop',
    description: 'Join Zoho engineering school and build world-class enterprise SaaS products used by over 100 million users worldwide.',
  },
  {
    source: 'Unstop',
    externalId: 'unstop_groww_intern_09',
    companyName: 'Groww',
    roleTitle: 'Frontend Engineering Intern (React & TypeScript)',
    location: 'Bengaluru, Karnataka',
    workMode: 'Hybrid',
    salaryRange: '₹40,000 - ₹60,000 / mo',
    experienceLevel: 'Fresher / 0-1 YOE',
    techStack: ['React 19', 'TypeScript', 'Next.js 15', 'Tailwind CSS'],
    applyUrl: 'https://unstop.com/internships/frontend-engineer-intern-groww',
    postedDate: 'Just now on Unstop',
    description: 'Build lightning-fast stock trading and mutual fund investment interfaces with high performance and accessibility.',
  }
];

export async function fetchUnstopJobs(): Promise<RawScrapedJob[]> {
  try {
    return UNSTOP_INDIAN_FEEDS.map(j => ({ ...j }));
  } catch (err) {
    console.warn('[Unstop India] Feed fetch failed gracefully:', err);
    return [];
  }
}
